drop table if exists gods;
drop table if exists powers;

create table if not exists gods( id serial primary key, name text, mythology text, demigod boolean);
create table if not exists powers( id int references gods(id), power1 varchar(30), power2 varchar(30) , power3 varchar(30), power4 varchar(30));

insert into gods( name, mythology, demigod )
values
( 'Zeus', 'Greek', false ),
( 'Hera', 'Greek', false ),
( 'Achilles', 'Greek', true ),
( 'Poseiden', 'Greek', false ),
( 'Demeter', 'Greek', false ),
( 'Ares', 'Greek', false ),
( 'Athena', 'Greek', false ), 
( 'Apollo', 'Greek', false ),
( 'Artemis', 'Greek', false ),
( 'Hephaestus', 'Greek', false ),
( 'Aphrodite', 'Greek', false ),
( 'Hermes', 'Greek', false ),
( 'Dionysus', 'Greek', true ),
( 'Hades', 'Greek', false ),
( 'Hypnos', 'Greek', false ),
( 'Nike', 'Greek', false ),
( 'Janus', 'Greek', false ),
( 'Anaeas', 'Greek', true ),
( 'Nemesis', 'Greek', false),
( 'Iris', 'Greek', false ),
( 'Hecate', 'Greek', false ),
( 'Tyche', 'Greek', false ),
( 'Jupiter', 'Roman', false ),
( 'Juno', 'Roman', false ),
( 'Neptune', 'Roman', false ),
( 'Hercules', 'Roman', true ),
( 'Minerva', 'Roman', false ),
( 'Mars', 'Roman', false ),
( 'Venus', 'Roman', false ),
( 'Apallo', 'Roman', false ),
( 'Diana', 'Roman', false ),
( 'Vulcan', 'Roman', false ),
( 'Mercury', 'Roman', false ),
( 'Ceres', 'Roman', false ),
( 'Vesta', 'Roman', false ),
( 'Bacchus', 'Roman', true );

drop table if exists powers;
create table if not exists powers(id int, power1 varchar(50), power2 text, power3 varchar(50), power4 text);
insert into powers(id, power1, power2, power3, power4)
values
(0, 'Lightning Bolts', 'Thunder', 'Weather', null),
(1, 'Bless and Curse Marriages', null, null, null),
(2, 'Invincibility', 'War', null, null),
(3, 'Water', 'Storms', 'Lightning', null),
(4, 'Agriculture', 'Fertility of Earth', null, null),
(5, 'Strength', 'Physicality', 'Battle', null),
(6, 'Defense', 'Wisdom', null, null),
(7,  'Prophecy', 'Healing', 'Light', null),
(8,  'Plagues', 'Healing', 'Protector of Children', null),
(9, 'Blacksmithing', null, null, null),
(10,  'Transformation', 'Love', null, null),
(11,'Speed', 'Flight', null, null),
(12,   'Teleportation', 'Transformation', 'Manipulation', null),
(13,  'Power Over the Dead','Riches', null, null),
(14,  'Sleep', null, null, null),
( 15, 'Victory', 'Flight', null, null),
(16,  'Time', null, null, null),
(17,  'Strength', 'Stamina', null, null),
(18,  'Balance', 'Justice', 'Retribution', null ),
(19, 'Messenger', 'Flight', null, null),
(20, 'Magic', 'Ghosts', 'Necromancy', null),
(21,  'Fortune', null, null, null),
(22, 'Light & Sky', 'Thunder', 'Lightning', null),
( 23, 'Leadership', 'Queen of the Gods', null, null ),
(24,  'Water','Storms','Earthquakes',  null),
( 25, 'Strength', null, null, null ),
( 26, 'Wisdom','War', 'Art', 'Commerce'),
(27,  'War', 'Agriculture', null, null),
( 28, 'Love', 'Beauty', 'Fertility', 'Victory'),
(29,  'Music', 'Prophecy', 'Healing', 'Plague'),
( 30, 'Goddess of the Hunt', 'Moon', 'Birthing', 'Speak to Animals'),
( 31,'Fire', 'Armor', 'Blacksmithing', null ),
(32, 'Transportation', 'Mercantile', 'Messenger', null),
(33, 'Agriculture', 'Maternal Love', null, null ),
( 34, 'Family', 'Home', null, null ),
( 35, 'Agriculture', 'Wine', 'Fertility', null);